### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/wrapweb#59]
```python
Aug 13 08:57:43 vm666.localdomain uwsgi[630]: [pid: 787|app: 0|req: 1449/2103] 131.228.2.20 () {36 vars in 476 bytes} [Mon Aug 13 08:57:43 2018] GET /v1/query/get_latest/gmock => generated 291 bytes in 3 msecs >
Aug 13 08:57:45 vm666.localdomain uwsgi[630]: [2018-08-13 08:57:45,208] ERROR in app: Exception on /v1/query/get_latest/gmock [GET]
Aug 13 08:57:45 vm666.localdomain uwsgi[630]: Traceback (most recent call last):
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:     response = self.full_dispatch_request()
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:     rv = self.handle_user_exception(e)
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:     reraise(exc_type, exc_value, tb)
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:     raise value
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:     rv = self.dispatch_request()
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:     return self.view_functions[rule.endpoint](**req.view_args)
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:   File "/usr/lib/python3.6/site-packages/wrapweb/api.py", line 45, in get_latest
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:     matches = _database().get_versions(project, latest=True)
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:   File "/usr/lib/python3.6/site-packages/mesonwrap/wrapdb.py", line 64, in get_versions
Aug 13 08:57:45 vm666.localdomain uwsgi[630]:     for r in c.fetchall())
Aug 13 08:57:45 vm666.localdomain uwsgi[630]: ValueError: max() arg is an empty sequence
```

**Comment by sarum9in** [comment]
Okay, so basically if the project does not exist it dumps a meaningless error. This must be fixed, however the fix is to just return a better error message instead.
